### ISSUE TITLE
When matrix group is collapsed only category id is shown

### ISSUE THREAD

**Issue by kruncher** [elivz/craft-single-cat#11]
![image](https://user-images.githubusercontent.com/554215/70099283-504ccc00-1626-11ea-9b15-08914c032288.png)

It would be much more user friendly if the category name was shown:

![image](https://user-images.githubusercontent.com/554215/70099320-68245000-1626-11ea-9b49-8c233e924f6a.png)

The built-in categories field shows the category names in this context.

Would you consider adding this for consistency with the built-in categories field?

**Comment by engram-design** [comment]
This has likely been a Craft update along the way, as this is working as expected:

<img width="209" alt="image" src="https://user-images.githubusercontent.com/1221575/203671604-6d5e3fc0-737b-443f-915e-8788f477d1b8.png">

Collapsed:

<img width="204" alt="image" src="https://user-images.githubusercontent.com/1221575/203671634-47b558b8-df7f-486a-a4d0-79a992f625eb.png">
