### ISSUE TITLE
Categories not pulling from correct site Id

### ISSUE THREAD

**Issue by jlawrence-yellostudio** [elivz/craft-single-cat#14]
Hi @elivz 

I've just discovered that the categories are not pulling the dropdown values from the correct site:

Within SingleCatField.php around Line 123:

```
        $categories = Category::find()
            ->groupId($source['criteria']['groupId'])
```
Needs to be:
```
        $categories = Category::find()
            ->siteId($this->targetSiteId($element))
            ->groupId($source['criteria']['groupId'])
```

Is it possible you could patch this in?

**Comment by elivz** [comment]
Good call! Fixed in 1.2.2.
