### ISSUE TITLE
Craft 4 Compatibility

### ISSUE THREAD

**Issue by stuible** [elivz/craft-single-cat#15]
This is such a useful little plugin and I would love to bring it forward into my Craft 4 projects.  Are there any plans to update it?

**Comment by theAdhocracy** [comment]
+1

**Comment by engram-design** [comment]
Just to chime in, we've added this to our [Craft 3 migration project](https://verbb.io/craft-3), as people are keen to see this plugin on Craft 4.

If you're no longer developing this plugin, we'd be happy to continue development at Verbb (including updating to Craft 4). If you'd like to go ahead, you can transfer this repository to myself `engram-design` and we can take it from here.

**Comment by johnfoland** [comment]
@elivz Please let Verbb take over upgrading this plugin to Craft 4; you know that they'll take good care of it.

**Comment by johnfoland** [comment]
@engram-design I see the votes were met on the [Craft 3 migration project page](https://verbb.io/craft-3), which is great!  Do we just need @elivz to respond now?

**Comment by engram-design** [comment]
@johnfoland yep! I’d rather not fork this and create a new plugin (just more work to migrate people) but it might come to that if there’s no response.

**Comment by elivz** [comment]
Hey @engram-design - Sorry I never got a notification about your first comment here. If you want to take it over and update, go for it. I can transfer it over.

**Comment by engram-design** [comment]
@elivz No problem, and thanks! You can transfer this repository to myself `engram-design` and we can take it from here.

**Comment by elivz** [comment]
I sent a transfer invite on Friday. Did it not work?

**Comment by engram-design** [comment]
@elivz Huh, I completely missed that email notification, sorry! Not sure how that happened, but are you able to trigger that again. Sorry for the inconvenience...

**Comment by engram-design** [comment]
Thanks @elivz all transferred across now, thanks!

**Comment by engram-design** [comment]
Added in [3.0.0](https://github.com/verbb/single-cat/releases/tag/3.0.0)
