### ISSUE TITLE
This field is not set to a valid category group.

### ISSUE THREAD

**Issue by leowebguy** [elivz/craft-single-cat#16]
### Describe the bug

I select the Single Cat field type and the Category

### Steps to reproduce

Just regular use... matter of fact it was working until I've update Craft.

![Screenshot 2023-05-08 at 5 21 13 PM](https://user-images.githubusercontent.com/8460020/236937983-b0578c3c-1318-4779-be87-66a99614806a.png)

![Screenshot 2023-05-08 at 5 21 25 PM](https://user-images.githubusercontent.com/8460020/236937995-5c19965c-fc90-403e-8cb3-144ce2743581.png)

![Screenshot 2023-05-08 at 5 13 50 PM](https://user-images.githubusercontent.com/8460020/236938016-2b1f46c9-7092-4dab-ad14-0c92769685f2.png)

### Craft CMS version

4.4.9

### Plugin version

3.0.1

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed in [3.0.2](https://github.com/verbb/single-cat/releases/tag/3.0.2)
