### ISSUE TITLE
TypeError: Argument #2 ($branchLimit) must be of type int, null given

### ISSUE THREAD

**Issue by adrianjean** [elivz/craft-single-cat#17]
### Describe the bug

Getting this error, and am unsure how to reproduce it. All I know is when I choose Single Cat as the field, in the CP I get this error:

```
craft\services\Structures::applyBranchLimitToElements(): Argument #2 ($branchLimit) must be of type int, null given, called in /srv/www/website.com/vendor/verbb/single-cat/src/fields/SingleCatField.php on line 63
```

### Steps to reproduce

Unsure how to reproduce. 

### Craft CMS version

4.4.9

### Plugin version

3.0.2

### Multi-site?

No

**Comment by engram-design** [comment]
Should be fixed in [3.0.3](https://github.com/verbb/single-cat/releases/tag/3.0.3)
