### ISSUE TITLE
Dropdown not being populated

### ISSUE THREAD

**Issue by rogertinch** [elivz/craft-single-cat#2]
I have a category group set up called "Product Types" with categories like Blu-ray, Book, etc. I created a new Single Cat field to pull from this group, but the dropdown is appearing empty when I try to use it in an entry. I also tried it with another category group and get the same results.

![screen shot 2018-11-05 at 7 43 41 am](https://user-images.githubusercontent.com/11000310/48001554-8ab80280-e0ce-11e8-9667-8d455a112536.png)

**Comment by elivz** [comment]
Interesting...I haven't been able to replicate this. Is this site public somewhere that I could take a quick look? Or could you send me a database dump so I can see how you have it set up? If either of those work, you can email me at [eli] (at) [elivz.com].

**Comment by rogertinch** [comment]
Just emailed you. Really appreciate you taking the time to dive in!

**Comment by elivz** [comment]
I believe this should be fixed now for you. It was a stupid mistake on my part – left some debugging code in place.

**Comment by rogertinch** [comment]
Yep, works great, thanks!
