### ISSUE TITLE
CraftQL Compatibility

### ISSUE THREAD

**Issue by rogertinch** [elivz/craft-single-cat#5]
Anything in the roadmap to have this be compatible with [CraftQL](https://github.com/markhuot/craftql)?

**Comment by elivz** [comment]
I haven't really looked into what that would take, since I don't use CraftQL myself. But I will definitely take a look. My plugin is really just an alternate UI on top of the native Categories field, so I would imagine it will be pretty easy to enable support.

**Comment by rogertinch** [comment]
If it helps, this is the error that GraphQL throws when trying to query a field using Single Cat:

```
{
  "errors": [
    {
      "message": "Field \"format\" of type \"String\" must not have a sub selection.",
      "category": "graphql",
      "locations": [
        {
          "line": 10,
          "column": 20
        }
      ]
    }
  ]
}
```

**Comment by elivz** [comment]
CraftQL support was added in [v1.2.0](https://github.com/elivz/craft-single-cat/releases/tag/1.2.0). Single Cat fields should now work identically to native Categories fields. Please let me know if you run into any problems.
