### ISSUE TITLE
Order of categories in dropdown

### ISSUE THREAD

**Issue by rogertinch** [elivz/craft-single-cat#9]
Would be cool if the order in the dropdown reflects a custom order. As of right now I don't know how they're currently being ordered.

**Comment by elivz** [comment]
It should! Are you saying that the order of categories in the dropdown is different from the order on the Categories page? I just did some testing and am unable to replicate this...I can drag to reorder the categories and on the next refresh of the Entry page, the drop-down is updated to match. Not sure what is going on...unless I am misunderstanding the problem.

**Comment by rogertinch** [comment]
Eli, my bad! I had my category sort set to title instead of structure. Please disregard!
